### ISSUE TITLE
Elastic 7.4

### ISSUE THREAD

**Issue by rklingaman** [SecurityRiskAdvisors/logstash-input-okta_system_log#3]
It looks like this currently doesn't support elastic 7.4. Not sure if there is any issues or not but I will be attempting to change the spec files up to that version and see if I can get it working.

**Comment by p-b--** [comment]
This is just an input plugin though, it doesn't directly talk to an elastic server. If you can give me steps to replicate, I'll try it out though!

**Comment by rklingaman** [comment]
I used the code and made a gem file and installed in on 6.8 and it works really good. However when installing that on 7.4 I get the following message:

ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-mixin-http_client":
  In snapshot (Gemfile.lock):
    logstash-mixin-http_client (= 7.0.0)

  In Gemfile:
    logstash-filter-http java was resolved to 1.0.2, which depends on
      logstash-mixin-http_client (>= 5.0.0, < 9.0.0) java

    logstash-input-http_poller java was resolved to 5.0.1, which depends on
      logstash-mixin-http_client (~> 7) java

    logstash-input-okta_system_log (= 0.9.0) java was resolved to 0.9.0, which depends on
      logstash-mixin-http_client (>= 2.2.4, < 7.0.0) java

    logstash-output-http java was resolved to 5.2.4, which depends on
      logstash-mixin-http_client (>= 6.0.0, < 8.0.0) java

Hoping it will work if I just up the versions in the code. But maybe better to get it installed without the gem file?

**Comment by p-b--** [comment]
Hey -- I updated the code and pushed it to Rubygems.

You should be able to get it to install with Logstash 7 now.

Thanks for the report!
