### ISSUE TITLE
Limit argument has no effect + request rate spikes

### ISSUE THREAD

**Issue by Ido-Moshe-Github** [SecurityRiskAdvisors/logstash-input-okta_system_log#6]
Hi,

First, thanks a lot for creating this plugin!

I have two issues related to data rates:

1. I get a lot of events per request - way over the limit I specify. When I send the same request using postman, I get the proper amount of events. I even took the request straight from plugin state file (at /usr/share/logstash/data/plugins/inputs/okta_system_log) and it worked properly. Just not with the plugin. 
Here's my pipeline:

```
input {
  okta_system_log {
    schedule            =>    { every => "1m" }
    limit                   =>    10
    filter                   =>    'severity ge "${OKTA_SEVERITY_LEVEL}"'
    auth_token_key  =>    "${OKTA_CLIENT_TOKEN}"
    hostname           =>    "${OKTA_DOMAIN}"
  }
}

output {
  stdout { 
    codec => json_lines
  }
}
```

The resulting query is  (from the state file):
https://<my domain>/api/v1/logs?limit=10&filter=severity+ge+%22INFO%22&after=1648112954504_1

I'm using Logstash docker image 8.0.1.

2. As you can see from the pipeline, there should be a request every 1 minute. This is indeed the case most of the time, but I sometimes see spikes of up to 12 requests per minute, and this triggers rate limiting on my OKTA account.
What can be the cause for this? How can I avoid it? (x-rate-limit?)

Thanks again.

**Comment by mbegan** [comment]
Limit dictates the page size.  Smaller pages == more requests.  You want max page sizes (1000) to reduce the number of API calls required to consume the number of logs that exist.

The Okta APIs use pagination to ensure requests are consumable by clients.  If you make a request to fetch logs (as shown in your question) and the resulting number of logs is greater than 10 the response is chunked into pages of 10.  This plugin follows the "next links" communicated by Okta to retrieve the remaining logs.

Schedule it to run every minute (the rate limit windows are set by the minute)
Configure it to use the max limit size (1000)

You'll get the most out of your rate limits with that setup, if you are still exhausting rate limits on a regular basis let me know.

**Comment by Ido-Moshe-Github** [comment]
Very interesting, I'll give it a try. I appreciate your responsiveness very much, thanks!

**Comment by Ido-Moshe-Github** [comment]
This seems to have solved my problem, I haven't seen any spikes since I changed the configuration according to your recommendation. Thanks again!

**Comment by p-b--** [comment]
@Ido-Moshe-Github  -- glad this worked out. You can also remove the parameter entirely, the plugin defaults to the maximum page size possible to reduce complexity of your configuration.
